# Generated by Django 3.2.9 on 2021-11-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal',
            new_name='MealClass',
        ),
    ]
